// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHJwRjQq0nUA7LRrQL80XJ-spZGWsOwLs',
    appId: '1:654995904748:android:2e7e1da02e9b271482adc9',
    messagingSenderId: '654995904748',
    projectId: 'hunting-call-perfection',
    storageBucket: 'hunting-call-perfection.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBhl5DK29N22yB5jonMr4Is60YfZrRWCQ',
    appId: '1:654995904748:ios:fc05c8c866caf70682adc9',
    messagingSenderId: '654995904748',
    projectId: 'hunting-call-perfection',
    storageBucket: 'hunting-call-perfection.firebasestorage.app',
    iosBundleId: 'com.example.huntingCallsPerfection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7zcpxfRV13kHdI6yUzIKzDxWcgWm-EFQ',
    appId: '1:654995904748:web:5079119d9b07508082adc9',
    messagingSenderId: '654995904748',
    projectId: 'hunting-call-perfection',
    authDomain: 'hunting-call-perfection.firebaseapp.com',
    storageBucket: 'hunting-call-perfection.firebasestorage.app',
    measurementId: 'G-SLPK7WY2SZ',
  );
}
